# Generated by Django 3.0.4 on 2020-03-20 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El campo dni debe contener 8 dígitos', regex='\\d{8}')])),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El campo teléfono debe contener 9 dígitos', regex='\\d{9}')])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
